"""Generated positional schema updates for newer nuverse master data.

Maps a game version to the tables whose positional field order differs
from the baseline in nuverse_positional_structures; each entry is
relative to that baseline. Distilled from Team-Haruki/Haruki-Sekai-API
Data/structures/<version>/nuverse_schema_bundle.json and verified
against the live blob by scripts/distill_nuverse_structures.py --update
(latest run: 6.4.0, master data cdnVersion 277). Regenerate
rather than edit.
"""

from typing import Any

# fmt: off
NUVERSE_POSITIONAL_STRUCTURE_UPDATES: dict[str, dict[str, list[Any]]] = {
    '6.4.0': {
        'billingShopItem': [
            'id',
            'seq',
            'billingShopItemType',
            'billingProductGroupId',
            'saleType',
            'name',
            'description',
            'billableLimitType',
            'billableLimitValue',
            'billableLimitResetIntervalType',
            'billableLimitResetIntervalValue',
            'assetbundleName',
            'resourceBoxId',
            'bonusResourceBoxId',
            'randomBoxGroupId',
            'label',
            'startAt',
            'endAt',
            'purchaseOption',
            'billingShopTabChildId',
        ],
        'billingShopItems': [
            'id',
            'seq',
            'billingShopItemType',
            'billingProductGroupId',
            'saleType',
            'name',
            'description',
            'billableLimitType',
            'billableLimitValue',
            'billableLimitResetIntervalType',
            'billableLimitResetIntervalValue',
            'assetbundleName',
            'resourceBoxId',
            'bonusResourceBoxId',
            'randomBoxGroupId',
            'label',
            'startAt',
            'endAt',
            'purchaseOption',
            'billingShopTabChildId',
        ],
        'event': [
            'id',
            'eventType',
            'name',
            'assetbundleName',
            'bgmAssetbundleName',
            'eventPointAssetbundleName',
            'eventOnlyComponentDisplayStartAt',
            'standbyScreenDisplayStartAt',
            'startAt',
            'aggregateAt',
            'rankingAnnounceAt',
            'distributionStartAt',
            'eventOnlyComponentDisplayEndAt',
            'closedAt',
            'distributionEndAt',
            'virtualLiveId',
            'unit',
            ['eventRankingRewardRanges', [
                'fromRank',
                'toRank',
                ['eventRankingRewards', [
                    'resourceBoxId',
                    'rewardConditionType',
                    'conditionValue',
                ]],
            ]],
            'eventBreakTimeId',
        ],
        'events': [
            'id',
            'eventType',
            'name',
            'assetbundleName',
            'bgmAssetbundleName',
            'eventPointAssetbundleName',
            'eventOnlyComponentDisplayStartAt',
            'standbyScreenDisplayStartAt',
            'startAt',
            'aggregateAt',
            'rankingAnnounceAt',
            'distributionStartAt',
            'eventOnlyComponentDisplayEndAt',
            'closedAt',
            'distributionEndAt',
            'virtualLiveId',
            'unit',
            ['eventRankingRewardRanges', [
                'fromRank',
                'toRank',
                ['eventRankingRewards', [
                    'resourceBoxId',
                    'rewardConditionType',
                    'conditionValue',
                ]],
            ]],
            'eventBreakTimeId',
        ],
        'gacha': [
            'id',
            'gachaType',
            'name',
            'seq',
            'assetbundleName',
            'startAt',
            'endAt',
            'isShowPeriod',
            'spinLimit',
            'gachaCeilItemId',
            'wishSelectCount',
            'wishFixedSelectCount',
            'wishLimitedSelectCount',
            'rateChoiceGachaWishGroupId',
            'gachaCharacterBonusGroupId',
            'isSelectCharacter',
            'gachaBonusId',
            'drawableGachaHour',
            ['gachaCardRarityRates', [
                'cardRarityType',
                'lotteryType',
                'rate',
            ]],
            ['gachaDetails', [
                'id',
                'gachaId',
                'cardId',
                'weight',
                'fixedBonusWeight',
                'isWish',
                'gachaDetailWishType',
            ]],
            ['gachaBehaviors', [
                'id',
                'gachaId',
                'gachaBehaviorType',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
                'executeLimit',
                'gachaExtraId',
                'groupId',
                'priority',
                'resourceCategory',
                'gachaSpinnableType',
            ]],
            ['gachaPickups', [
                'gachaId',
                'cardId',
            ]],
            'gachaInformation',
            'dailySpinLimit',
            'gachaBonusItemReceivableRewardGroupId',
            'gachaFreebieGroupId',
        ],
        'gachas': [
            'id',
            'gachaType',
            'name',
            'seq',
            'assetbundleName',
            'startAt',
            'endAt',
            'isShowPeriod',
            'spinLimit',
            'gachaCeilItemId',
            'wishSelectCount',
            'wishFixedSelectCount',
            'wishLimitedSelectCount',
            'rateChoiceGachaWishGroupId',
            'gachaCharacterBonusGroupId',
            'isSelectCharacter',
            'gachaBonusId',
            'drawableGachaHour',
            ['gachaCardRarityRates', [
                'cardRarityType',
                'lotteryType',
                'rate',
            ]],
            ['gachaDetails', [
                'id',
                'gachaId',
                'cardId',
                'weight',
                'fixedBonusWeight',
                'isWish',
                'gachaDetailWishType',
            ]],
            ['gachaBehaviors', [
                'id',
                'gachaId',
                'gachaBehaviorType',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
                'executeLimit',
                'gachaExtraId',
                'groupId',
                'priority',
                'resourceCategory',
                'gachaSpinnableType',
            ]],
            ['gachaPickups', [
                'gachaId',
                'cardId',
            ]],
            ['gachaInformation', ('gachaId', 'summary', 'description', 'bubbleAssetbundleName', 'bubbleText',)],
            'dailySpinLimit',
            'gachaBonusItemReceivableRewardGroupId',
            'gachaFreebieGroupId',
        ],
        'mysekaiFixture': [
            'id',
            'mysekaiFixtureType',
            'name',
            'pronunciation',
            'flavorText',
            'seq',
            'gridSize',
            'colorCode',
            'mysekaiFixtureMainGenreId',
            'mysekaiFixtureSubGenreId',
            'mysekaiFixtureHandleType',
            'mysekaiSettableSiteType',
            'mysekaiSettableLayoutType',
            'mysekaiFixturePutType',
            ['mysekaiFixtureAnotherColors', [
                'textureId',
                'colorCode',
            ]],
            'mysekaiFixtureGameCharacterGroupPerformanceBonusId',
            'mysekaiFixturePutSoundId',
            'mysekaiFixtureFootstepId',
            'mysekaiFixtureTagGroup',
            'isAssembled',
            'isDisassembled',
            'mysekaiFixturePlayerActionType',
            'isGameCharacterAction',
            'assetbundleName',
            'firstPutCost',
            'secondPutCost',
        ],
        'mysekaiFixtures': [
            'id',
            'mysekaiFixtureType',
            'name',
            'pronunciation',
            'flavorText',
            'seq',
            'gridSize',
            'colorCode',
            'mysekaiFixtureMainGenreId',
            'mysekaiFixtureSubGenreId',
            'mysekaiFixtureHandleType',
            'mysekaiSettableSiteType',
            'mysekaiSettableLayoutType',
            'mysekaiFixturePutType',
            ['mysekaiFixtureAnotherColors', [
                'textureId',
                'colorCode',
            ]],
            'mysekaiFixtureGameCharacterGroupPerformanceBonusId',
            'mysekaiFixturePutSoundId',
            'mysekaiFixtureFootstepId',
            'mysekaiFixtureTagGroup',
            'isAssembled',
            'isDisassembled',
            'mysekaiFixturePlayerActionType',
            'isGameCharacterAction',
            'assetbundleName',
            'firstPutCost',
            'secondPutCost',
        ],
    },
}
