"""Generated positional schemas for nuverse (cn/tw/kr) master data.

Field orders for tables the upstream source delivers as positional
arrays. Distilled from Team-Haruki/Haruki-Sekai-API
Data/structures/nuverse_schema_bundle.json (master data cdnVersion 273)
and verified against the live blob by
scripts/distill_nuverse_structures.py. Regenerate rather than edit;
the one intentional divergence (cardCostume3ds isInitialObtainHair)
is recorded in EXTRA_TRAILING_FIELDS inside the distiller.
"""

from typing import Any

# fmt: off
NUVERSE_POSITIONAL_STRUCTURES: dict[str, list[Any]] = (
{
        'actionSet': [
            'id',
            'areaId',
            'actionSetType',
            'isNextGrade',
            'scenarioId',
            'scriptId',
            'specialSeasonId',
            'characterIds',
            'archiveDisplayType',
            'archivePublishedAt',
            'releaseConditionId',
        ],
        'actionSets': [
            'id',
            'areaId',
            'actionSetType',
            'isNextGrade',
            'scenarioId',
            'scriptId',
            'specialSeasonId',
            'characterIds',
            'archiveDisplayType',
            'archivePublishedAt',
            'releaseConditionId',
        ],
        'aprilFoolReview': [
            'id',
            'name',
            'releaseConditionId',
            'unlockType',
            'unlockMaterialId',
        ],
        'aprilFoolReviews': [
            'id',
            'name',
            'releaseConditionId',
            'unlockType',
            'unlockMaterialId',
        ],
        'areaItemLevel': [
            'areaItemId',
            'level',
            'targetUnit',
            'targetCardAttr',
            'targetGameCharacterId',
            'power1BonusRate',
            'power1AllMatchBonusRate',
            'power2BonusRate',
            'power2AllMatchBonusRate',
            'power3BonusRate',
            'power3AllMatchBonusRate',
            'sentence',
        ],
        'areaItemLevels': [
            'areaItemId',
            'level',
            'targetUnit',
            'targetCardAttr',
            'targetGameCharacterId',
            'power1BonusRate',
            'power1AllMatchBonusRate',
            'power2BonusRate',
            'power2AllMatchBonusRate',
            'power3BonusRate',
            'power3AllMatchBonusRate',
            'sentence',
        ],
        'billingShopItem': [
            'id',
            'seq',
            'billingShopItemType',
            'billingProductGroupId',
            'saleType',
            'name',
            'description',
            'billableLimitType',
            'billableLimitValue',
            'billableLimitResetIntervalType',
            'billableLimitResetIntervalValue',
            'assetbundleName',
            'resourceBoxId',
            'bonusResourceBoxId',
            'label',
            'startAt',
            'endAt',
            'purchaseOption',
            'billingShopTabChildId',
        ],
        'billingShopItems': [
            'id',
            'seq',
            'billingShopItemType',
            'billingProductGroupId',
            'saleType',
            'name',
            'description',
            'billableLimitType',
            'billableLimitValue',
            'billableLimitResetIntervalType',
            'billableLimitResetIntervalValue',
            'assetbundleName',
            'resourceBoxId',
            'bonusResourceBoxId',
            'label',
            'startAt',
            'endAt',
            'purchaseOption',
            'billingShopTabChildId',
        ],
        'bondsHonor': [
            'id',
            'seq',
            'bondsGroupId',
            'gameCharacterUnitId1',
            'gameCharacterUnitId2',
            'honorRarity',
            'name',
            'pronunciation',
            'description',
            ['levels', [
                'id',
                'bondsHonorId',
                'level',
                'description',
            ]],
            'configurableUnitVirtualSinger',
        ],
        'bondsHonorLevel': [
            'id',
            'bondsHonorId',
            'level',
            'description',
        ],
        'bondsHonorLevels': [
            'id',
            'bondsHonorId',
            'level',
            'description',
        ],
        'bondsHonorWord': [
            'id',
            'seq',
            'bondsGroupId',
            'assetbundleName',
            'name',
            'description',
        ],
        'bondsHonorWords': [
            'id',
            'seq',
            'bondsGroupId',
            'assetbundleName',
            'name',
            'description',
        ],
        'bondsHonors': [
            'id',
            'seq',
            'bondsGroupId',
            'gameCharacterUnitId1',
            'gameCharacterUnitId2',
            'honorRarity',
            'name',
            'pronunciation',
            'description',
            ['levels', [
                'id',
                'bondsHonorId',
                'level',
                'description',
            ]],
            'configurableUnitVirtualSinger',
        ],
        'card': [
            'id',
            'seq',
            'characterId',
            'cardRarityType',
            'specialTrainingPower1BonusFixed',
            'specialTrainingPower2BonusFixed',
            'specialTrainingPower3BonusFixed',
            'attr',
            'supportUnit',
            'skillId',
            'cardSkillName',
            'specialTrainingSkillId',
            'specialTrainingSkillName',
            'prefix',
            'assetbundleName',
            'gachaPhrase',
            'releaseAt',
            'archiveDisplayType',
            'archivePublishedAt',
            'cardSupplyId',
            'cardParameters',
            ['specialTrainingCosts', [
                'cardId',
                'seq',
                'cost',
            ]],
            'specialTrainingRewardResourceBoxId',
            ['masterLessonAchieveResources', ['masterRank', ['resources', [
                'resourceId',
                'resourceType',
                'resourceLevel',
                'quantity',
            ]]]],
            'initialSpecialTrainingStatus',
        ],
        'cardCostume3d': [
            'cardId',
            'costume3dId',
        ],
        'cardCostume3ds': [
            'cardId',
            'costume3dId',
            'isInitialObtainHair',
        ],
        'cardEpisode': [
            'id',
            'cardId',
            'title',
            'scenarioId',
            'releaseConditionId',
            'power1BonusFixed',
            'power2BonusFixed',
            'power3BonusFixed',
            ['costs', [
                'resourceId',
                'resourceType',
                'resourceLevel',
                'quantity',
            ]],
            'cardEpisodePartType',
        ],
        'cardEpisodes': [
            'id',
            'cardId',
            'title',
            'scenarioId',
            'releaseConditionId',
            'power1BonusFixed',
            'power2BonusFixed',
            'power3BonusFixed',
            ['costs', [
                'resourceId',
                'resourceType',
                'resourceLevel',
                'quantity',
            ]],
            'cardEpisodePartType',
        ],
        'cards': [
            'id',
            'seq',
            'characterId',
            'cardRarityType',
            'specialTrainingPower1BonusFixed',
            'specialTrainingPower2BonusFixed',
            'specialTrainingPower3BonusFixed',
            'attr',
            'supportUnit',
            'skillId',
            'cardSkillName',
            'specialTrainingSkillId',
            'specialTrainingSkillName',
            'prefix',
            'assetbundleName',
            'gachaPhrase',
            'releaseAt',
            'archiveDisplayType',
            'archivePublishedAt',
            'cardSupplyId',
            'cardParameters',
            ['specialTrainingCosts', [
                'cardId',
                'seq',
                'cost',
            ]],
            'specialTrainingRewardResourceBoxId',
            ['masterLessonAchieveResources', ['masterRank', ['resources', [
                'resourceId',
                'resourceType',
                'resourceLevel',
                'quantity',
            ]]]],
            'initialSpecialTrainingStatus',
        ],
        'challengeLiveHighScoreReward': [
            'id',
            'characterId',
            'highScore',
            'resourceBoxId',
        ],
        'challengeLiveHighScoreRewards': [
            'id',
            'characterId',
            'highScore',
            'resourceBoxId',
        ],
        'challengeLiveStage': [
            'characterId',
            'rank',
            'nextStageChallengePoint',
        ],
        'challengeLiveStages': [
            'characterId',
            'rank',
            'nextStageChallengePoint',
        ],
        'character3d': [
            'id',
            'characterId',
            'unit',
            'headCostume3dId',
            'hairCostume3dId',
            'bodyCostume3dId',
            'lookAtLimitX',
            'lookAtLimitY',
            'name',
        ],
        'character3ds': [
            'id',
            'characterId',
            'unit',
            'headCostume3dId',
            'hairCostume3dId',
            'bodyCostume3dId',
            'lookAtLimitX',
            'lookAtLimitY',
            'name',
        ],
        'characterArchiveMysekaiCharacterTalkGroup': [
            'id',
            'seq',
            'archiveDisplayType',
            'characterArchiveMysekaiCharacterTalkGroupTagId',
        ],
        'characterArchiveMysekaiCharacterTalkGroups': [
            'id',
            'seq',
            'archiveDisplayType',
            'characterArchiveMysekaiCharacterTalkGroupTagId',
        ],
        'characterArchiveVoice': [
            'id',
            'groupId',
            'gameCharacterId',
            'unit',
            'characterArchiveVoiceType',
            'displayPhrase',
            'displayPhrase2',
            'characterArchiveVoiceTagId',
            'externalId',
            'assetName',
            'isNextGrade',
            'displayStartAt',
        ],
        'characterArchiveVoices': [
            'id',
            'groupId',
            'gameCharacterId',
            'unit',
            'characterArchiveVoiceType',
            'displayPhrase',
            'displayPhrase2',
            'characterArchiveVoiceTagId',
            'externalId',
            'assetName',
            'isNextGrade',
            'displayStartAt',
        ],
        'characterRank': [
            'id',
            'characterId',
            'characterRank',
            'power1BonusRate',
            'power2BonusRate',
            'power3BonusRate',
            'rewardResourceBoxIds',
            ['characterRankAchieveResources', [
                ['resources', [
                    'resourceId',
                    'resourceType',
                    'resourceLevel',
                    'quantity',
                ]],
            ]],
        ],
        'characterRanks': [
            'id',
            'characterId',
            'characterRank',
            'power1BonusRate',
            'power2BonusRate',
            'power3BonusRate',
            'rewardResourceBoxIds',
            ['characterRankAchieveResources', [
                ['resources', [
                    'resourceId',
                    'resourceType',
                    'resourceLevel',
                    'quantity',
                ]],
            ]],
        ],
        'cheerfulCarnivalPartyName': [
            'id',
            'partyName',
            'gameCharacterUnitId1',
            'gameCharacterUnitId2',
            'gameCharacterUnitId3',
            'gameCharacterUnitId4',
            'gameCharacterUnitId5',
        ],
        'cheerfulCarnivalPartyNames': [
            'id',
            'partyName',
            'gameCharacterUnitId1',
            'gameCharacterUnitId2',
            'gameCharacterUnitId3',
            'gameCharacterUnitId4',
            'gameCharacterUnitId5',
        ],
        'costume3d': [
            'id',
            'seq',
            'costume3dGroupId',
            'costume3dType',
            'name',
            'partType',
            'colorId',
            'colorName',
            'characterId',
            'costume3dRarity',
            'howToObtain',
            'assetbundleName',
            'designer',
            'publishedAt',
            'archiveDisplayType',
            'archivePublishedAt',
        ],
        'costume3dColor': [
            'id',
            'name',
        ],
        'costume3dColors': [
            'id',
            'name',
        ],
        'costume3dFittings': [
            'billingShopItemId',
            'characterId',
            'hairCostume3dId',
        ],
        'costume3dFittingses': [
            'billingShopItemId',
            'characterId',
            'hairCostume3dId',
        ],
        'costume3dGroup': [
            'groupId',
            'name',
            'characterId',
            'rarity',
            'howToObtain',
            'designer',
            'publishedAt',
            'archiveDisplayType',
            'archivePublishedAt',
        ],
        'costume3dGroups': [
            'groupId',
            'name',
            'characterId',
            'rarity',
            'howToObtain',
            'designer',
            'publishedAt',
            'archiveDisplayType',
            'archivePublishedAt',
        ],
        'costume3dModelDefaultHair': [
            'id',
            'headCostume3dId',
            'hairCostume3dId',
            'unit',
        ],
        'costume3dModelDefaultHairs': [
            'id',
            'headCostume3dId',
            'hairCostume3dId',
            'unit',
        ],
        'costume3dModelNotAvailablePattern': [
            'id',
            'headCostume3dId',
            'hairCostume3dId',
            'unit',
        ],
        'costume3dModelNotAvailablePatterns': [
            'id',
            'headCostume3dId',
            'hairCostume3dId',
            'unit',
        ],
        'costume3ds': [
            'id',
            'seq',
            'costume3dGroupId',
            'costume3dType',
            'name',
            'partType',
            'colorId',
            'colorName',
            'characterId',
            'costume3dRarity',
            'howToObtain',
            'assetbundleName',
            'designer',
            'publishedAt',
            'archiveDisplayType',
            'archivePublishedAt',
        ],
        'customProfileCollectionGacha': [
            'id',
            'name',
            'startAt',
            'endAt',
            'assetbundleName',
            'description',
            'notice',
            'customProfileGachaCategory',
            ['customProfileGachaBehaviors', [
                'id',
                'seq',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
            ]],
            ['customProfileGachaDetails', [
                'id',
                'customProfileResourceType',
                'customProfileResourceId',
                'weight',
            ]],
        ],
        'customProfileCollectionGachaBehavior': [
            'id',
            'seq',
            'costResourceType',
            'costResourceId',
            'costResourceQuantity',
            'spinCount',
        ],
        'customProfileCollectionGachaBehaviors': [
            'id',
            'seq',
            'costResourceType',
            'costResourceId',
            'costResourceQuantity',
            'spinCount',
        ],
        'customProfileCollectionGachaDetail': [
            'id',
            'customProfileResourceType',
            'customProfileResourceId',
            'weight',
        ],
        'customProfileCollectionGachaDetails': [
            'id',
            'customProfileResourceType',
            'customProfileResourceId',
            'weight',
        ],
        'customProfileCollectionGachas': [
            'id',
            'name',
            'startAt',
            'endAt',
            'assetbundleName',
            'description',
            'notice',
            'customProfileGachaCategory',
            ['customProfileGachaBehaviors', [
                'id',
                'seq',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
            ]],
            ['customProfileGachaDetails', [
                'id',
                'customProfileResourceType',
                'customProfileResourceId',
                'weight',
            ]],
        ],
        'customProfileCollectionResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'customProfileEtcResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'customProfileGachaBehaviors': [
            'id',
            'seq',
            'costResourceType',
            'costResourceId',
            'costResourceQuantity',
            'spinCount',
        ],
        'customProfileGachaDetails': [
            'id',
            'customProfileResourceType',
            'customProfileResourceId',
            'weight',
        ],
        'customProfileGachas': [
            'id',
            'name',
            'startAt',
            'endAt',
            'assetbundleName',
            'description',
            'notice',
            'customProfileGachaCategory',
            ['customProfileGachaBehaviors', [
                'id',
                'seq',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
            ]],
            ['customProfileGachaDetails', [
                'id',
                'customProfileResourceType',
                'customProfileResourceId',
                'weight',
            ]],
        ],
        'customProfileGeneralBackgroundResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'customProfileMemberStandingPictureResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'customProfilePlayerInfoResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'customProfileShapeResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'customProfileStoryBackgroundResources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'episodeCharacter': [
            'id',
            'seq',
            'character2dId',
            'storyType',
            'episodeId',
        ],
        'episodeCharacters': [
            'id',
            'seq',
            'character2dId',
            'storyType',
            'episodeId',
        ],
        'event': [
            'id',
            'eventType',
            'name',
            'assetbundleName',
            'bgmAssetbundleName',
            'eventPointAssetbundleName',
            'eventOnlyComponentDisplayStartAt',
            'standbyScreenDisplayStartAt',
            'startAt',
            'aggregateAt',
            'rankingAnnounceAt',
            'distributionStartAt',
            'eventOnlyComponentDisplayEndAt',
            'closedAt',
            'distributionEndAt',
            'virtualLiveId',
            'unit',
            ['eventRankingRewardRanges', [
                'fromRank',
                'toRank',
                ['eventRankingRewards', [
                    'resourceBoxId',
                    'rewardConditionType',
                    'conditionValue',
                ]],
            ]],
        ],
        'eventDeckBonus': [
            'id',
            'eventId',
            'gameCharacterUnitId',
            'cardAttr',
            'bonusRate',
        ],
        'eventDeckBonuses': [
            'id',
            'eventId',
            'gameCharacterUnitId',
            'cardAttr',
            'bonusRate',
        ],
        'eventExchangeSummaries': [
            'id',
            'eventId',
            'startAt',
            'endAt',
            ['eventExchanges', [
                'id',
                'eventExchangeSummaryId',
                'gameCharacterId',
                'seq',
                'resourceBoxId',
                'exchangeLimit',
                'eventExchangeCost',
            ]],
            'assetbundleName',
        ],
        'eventExchangeSummary': [
            'id',
            'eventId',
            'startAt',
            'endAt',
            ['eventExchanges', [
                'id',
                'eventExchangeSummaryId',
                'gameCharacterId',
                'seq',
                'resourceBoxId',
                'exchangeLimit',
                'eventExchangeCost',
            ]],
            'assetbundleName',
        ],
        'eventStories': [
            'id',
            'eventId',
            'outline',
            'bannerGameCharacterUnitId',
            'assetbundleName',
            ['eventStoryEpisodes', [
                'id',
                'eventStoryId',
                'gameCharacterId',
                'episodeNo',
                'title',
                'assetbundleName',
                'scenarioId',
                'releaseConditionId',
                ['episodeRewards', [
                    'startAt',
                    'endAt',
                    'resourceBoxId',
                ]],
            ]],
        ],
        'eventStory': [
            'id',
            'eventId',
            'outline',
            'bannerGameCharacterUnitId',
            'assetbundleName',
            ['eventStoryEpisodes', [
                'id',
                'eventStoryId',
                'gameCharacterId',
                'episodeNo',
                'title',
                'assetbundleName',
                'scenarioId',
                'releaseConditionId',
                ['episodeRewards', [
                    'startAt',
                    'endAt',
                    'resourceBoxId',
                ]],
            ]],
        ],
        'events': [
            'id',
            'eventType',
            'name',
            'assetbundleName',
            'bgmAssetbundleName',
            'eventPointAssetbundleName',
            'eventOnlyComponentDisplayStartAt',
            'standbyScreenDisplayStartAt',
            'startAt',
            'aggregateAt',
            'rankingAnnounceAt',
            'distributionStartAt',
            'eventOnlyComponentDisplayEndAt',
            'closedAt',
            'distributionEndAt',
            'virtualLiveId',
            'unit',
            ['eventRankingRewardRanges', [
                'fromRank',
                'toRank',
                ['eventRankingRewards', [
                    'resourceBoxId',
                    'rewardConditionType',
                    'conditionValue',
                ]],
            ]],
        ],
        'gacha': [
            'id',
            'gachaType',
            'name',
            'seq',
            'assetbundleName',
            'startAt',
            'endAt',
            'isShowPeriod',
            'spinLimit',
            'gachaCeilItemId',
            'wishSelectCount',
            'wishFixedSelectCount',
            'wishLimitedSelectCount',
            'gachaBonusId',
            'drawableGachaHour',
            ['gachaCardRarityRates', [
                'cardRarityType',
                'lotteryType',
                'rate',
            ]],
            ['gachaDetails', [
                'id',
                'gachaId',
                'cardId',
                'weight',
                'fixedBonusWeight',
                'isWish',
                'gachaDetailWishType',
            ]],
            ['gachaBehaviors', [
                'id',
                'gachaId',
                'gachaBehaviorType',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
                'executeLimit',
                'gachaExtraId',
                'groupId',
                'priority',
                'resourceCategory',
                'gachaSpinnableType',
            ]],
            ['gachaPickups', [
                'gachaId',
                'cardId',
            ]],
            'gachaInformation',
            'dailySpinLimit',
            'gachaBonusItemReceivableRewardGroupId',
            'gachaFreebieGroupId',
        ],
        'gachaBehavior': [
            'id',
            'gachaId',
            'gachaBehaviorType',
            'costResourceType',
            'costResourceId',
            'costResourceQuantity',
            'spinCount',
            'executeLimit',
            'gachaExtraId',
            'groupId',
            'priority',
            'resourceCategory',
            'gachaSpinnableType',
        ],
        'gachaBehaviors': [
            'id',
            'gachaId',
            'gachaBehaviorType',
            'costResourceType',
            'costResourceId',
            'costResourceQuantity',
            'spinCount',
            'executeLimit',
            'gachaExtraId',
            'groupId',
            'priority',
            'resourceCategory',
            'gachaSpinnableType',
        ],
        'gachaCardRarityRate': [
            'cardRarityType',
            'lotteryType',
            'rate',
        ],
        'gachaCardRarityRates': [
            'cardRarityType',
            'lotteryType',
            'rate',
        ],
        'gachaCeilExchange': [
            'id',
            'gachaCeilExchangeSummaryId',
            'seq',
            'resourceBoxId',
            'exchangeLimit',
            'gachaCeilExchangeLabelType',
            'substituteLimit',
            'gachaCeilExchangeCost',
            ['substituteCosts', [
                'id',
                'resourceType',
                'resourceId',
                'substituteQuantity',
            ]],
        ],
        'gachaCeilExchangeCost': [
            'quantity',
            'resourceType',
            'resourceId',
        ],
        'gachaCeilExchangeCosts': [
            'quantity',
            'resourceType',
            'resourceId',
        ],
        'gachaCeilExchangeSubstituteCost': [
            'id',
            'resourceType',
            'resourceId',
            'substituteQuantity',
        ],
        'gachaCeilExchangeSubstituteCosts': [
            'id',
            'resourceType',
            'resourceId',
            'substituteQuantity',
        ],
        'gachaCeilExchangeSummaries': [
            'id',
            'seq',
            'assetbundleName',
            'startAt',
            'endAt',
            ['gachaCeilExchanges', [
                'id',
                'gachaCeilExchangeSummaryId',
                'seq',
                'resourceBoxId',
                'exchangeLimit',
                'gachaCeilExchangeLabelType',
                'substituteLimit',
                'gachaCeilExchangeCost',
                ['substituteCosts', [
                    'id',
                    'resourceType',
                    'resourceId',
                    'substituteQuantity',
                ]],
            ]],
            'gachaCeilItemId',
        ],
        'gachaCeilExchangeSummary': [
            'id',
            'seq',
            'assetbundleName',
            'startAt',
            'endAt',
            ['gachaCeilExchanges', [
                'id',
                'gachaCeilExchangeSummaryId',
                'seq',
                'resourceBoxId',
                'exchangeLimit',
                'gachaCeilExchangeLabelType',
                'substituteLimit',
                'gachaCeilExchangeCost',
                ['substituteCosts', [
                    'id',
                    'resourceType',
                    'resourceId',
                    'substituteQuantity',
                ]],
            ]],
            'gachaCeilItemId',
        ],
        'gachaCeilExchanges': [
            'id',
            'gachaCeilExchangeSummaryId',
            'seq',
            'resourceBoxId',
            'exchangeLimit',
            'gachaCeilExchangeLabelType',
            'substituteLimit',
            'gachaCeilExchangeCost',
            ['substituteCosts', [
                'id',
                'resourceType',
                'resourceId',
                'substituteQuantity',
            ]],
        ],
        'gachaDetail': [
            'id',
            'gachaId',
            'cardId',
            'weight',
            'fixedBonusWeight',
            'isWish',
            'gachaDetailWishType',
        ],
        'gachaDetails': [
            'id',
            'gachaId',
            'cardId',
            'weight',
            'fixedBonusWeight',
            'isWish',
            'gachaDetailWishType',
        ],
        'gachaInformation': [
            'gachaId',
            'summary',
            'description',
            'bubbleAssetbundleName',
            'bubbleText',
        ],
        'gachaInformations': [
            'gachaId',
            'summary',
            'description',
            'bubbleAssetbundleName',
            'bubbleText',
        ],
        'gachaPickup': [
            'gachaId',
            'cardId',
        ],
        'gachaPickups': [
            'gachaId',
            'cardId',
        ],
        'gachas': [
            'id',
            'gachaType',
            'name',
            'seq',
            'assetbundleName',
            'startAt',
            'endAt',
            'isShowPeriod',
            'spinLimit',
            'gachaCeilItemId',
            'wishSelectCount',
            'wishFixedSelectCount',
            'wishLimitedSelectCount',
            'gachaBonusId',
            'drawableGachaHour',
            ['gachaCardRarityRates', [
                'cardRarityType',
                'lotteryType',
                'rate',
            ]],
            ['gachaDetails', [
                'id',
                'gachaId',
                'cardId',
                'weight',
                'fixedBonusWeight',
                'isWish',
                'gachaDetailWishType',
            ]],
            ['gachaBehaviors', [
                'id',
                'gachaId',
                'gachaBehaviorType',
                'costResourceType',
                'costResourceId',
                'costResourceQuantity',
                'spinCount',
                'executeLimit',
                'gachaExtraId',
                'groupId',
                'priority',
                'resourceCategory',
                'gachaSpinnableType',
            ]],
            ['gachaPickups', [
                'gachaId',
                'cardId',
            ]],
            ['gachaInformation', ('gachaId', 'summary', 'description', 'bubbleAssetbundleName', 'bubbleText',)],
            'dailySpinLimit',
            'gachaBonusItemReceivableRewardGroupId',
            'gachaFreebieGroupId',
        ],
        'honor': [
            'id',
            'seq',
            'groupId',
            'honorRarity',
            'name',
            'assetbundleName',
            'honorTypeId',
            'honorMissionType',
            'startAt',
            ['levels', [
                'level',
                'bonus',
                'description',
                'startAt',
                'assetbundleName',
                'honorRarity',
            ]],
        ],
        'honorLevel': [
            'level',
            'bonus',
            'description',
            'startAt',
            'assetbundleName',
            'honorRarity',
        ],
        'honorLevels': [
            'level',
            'bonus',
            'description',
            'startAt',
            'assetbundleName',
            'honorRarity',
        ],
        'honorMission': [
            'id',
            'seq',
            'honorMissionType',
            'requirement',
            'sentence',
            ['rewards', [
                'resourceBoxId',
            ]],
            'startAt',
        ],
        'honorMissions': [
            'id',
            'seq',
            'honorMissionType',
            'requirement',
            'sentence',
            ['rewards', [
                'resourceBoxId',
            ]],
            'startAt',
        ],
        'honors': [
            'id',
            'seq',
            'groupId',
            'honorRarity',
            'name',
            'assetbundleName',
            'honorTypeId',
            'honorMissionType',
            'startAt',
            ['levels', [
                'level',
                'bonus',
                'description',
                'startAt',
                'assetbundleName',
                'honorRarity',
            ]],
        ],
        'jewelShowDialogue': [
            'id',
            'seq',
            'name',
            'assetbundleName',
            'startAt',
            'endAt',
            ['behaviors', [
                'seq',
                'billingShopItemId',
            ]],
        ],
        'jewelShowDialogueBehavior': [
            'seq',
            'billingShopItemId',
        ],
        'jewelShowDialogueBehaviors': [
            'seq',
            'billingShopItemId',
        ],
        'jewelShowDialogues': [
            'id',
            'seq',
            'name',
            'assetbundleName',
            'startAt',
            'endAt',
            ['behaviors', [
                'seq',
                'billingShopItemId',
            ]],
        ],
        'liveMission': [
            'id',
            'liveMissionPeriodId',
            'liveMissionType',
            'requirement',
            ['rewards', [
                'resourceBoxId',
            ]],
        ],
        'liveMissions': [
            'id',
            'liveMissionPeriodId',
            'liveMissionType',
            'requirement',
            ['rewards', [
                'resourceBoxId',
            ]],
        ],
        'masterLessonAchieveResource': ['masterRank', ['resources', [
            'resourceId',
            'resourceType',
            'resourceLevel',
            'quantity',
        ]]],
        'masterLessonAchieveResources': ['masterRank', ['resources', [
            'resourceId',
            'resourceType',
            'resourceLevel',
            'quantity',
        ]]],
        'masterLessonReward': [
            'cardId',
            'masterRank',
            'resourceBoxId',
            'id',
        ],
        'masterLessonRewards': [
            'cardId',
            'masterRank',
            'resourceBoxId',
            'id',
        ],
        'materialExchange': [
            'id',
            'materialExchangeSummaryId',
            'seq',
            'displayName',
            'isDisplayQuantity',
            'thumbnailAssetbundleName',
            'resourceBoxId',
            'refreshCycle',
            'exchangeLimit',
            'startAt',
            'endAt',
            ['costs', [
                'materialExchangeId',
                'costGroupId',
                'seq',
                'resourceType',
                'resourceId',
                'quantity',
            ]],
            ['materialExchangeRelationParents', [
                'id',
                'description',
                'assetbundleName',
                ['materialExchangeRelationChildren', [
                    'materialExchangeId',
                    'materialExchangeCostGroupId',
                ]],
            ]],
        ],
        'materialExchangeCost': [
            'materialExchangeId',
            'costGroupId',
            'seq',
            'resourceType',
            'resourceId',
            'quantity',
        ],
        'materialExchangeCosts': [
            'materialExchangeId',
            'costGroupId',
            'seq',
            'resourceType',
            'resourceId',
            'quantity',
        ],
        'materialExchangeRelationChild': [
            'materialExchangeId',
            'materialExchangeCostGroupId',
        ],
        'materialExchangeRelationChilds': [
            'materialExchangeId',
            'materialExchangeCostGroupId',
        ],
        'materialExchangeRelationParent': [
            'id',
            'description',
            'assetbundleName',
            ['materialExchangeRelationChildren', [
                'materialExchangeId',
                'materialExchangeCostGroupId',
            ]],
        ],
        'materialExchangeRelationParents': [
            'id',
            'description',
            'assetbundleName',
            ['materialExchangeRelationChildren', [
                'materialExchangeId',
                'materialExchangeCostGroupId',
            ]],
        ],
        'materialExchangeSummaries': [
            'id',
            'seq',
            'exchangeCategory',
            'materialExchangeType',
            'materialExchangeDisplayResourceGroupId',
            'name',
            'assetbundleName',
            'startAt',
            'endAt',
            'notificationRemainHour',
            ['materialExchanges', [
                'id',
                'materialExchangeSummaryId',
                'seq',
                'displayName',
                'isDisplayQuantity',
                'thumbnailAssetbundleName',
                'resourceBoxId',
                'refreshCycle',
                'exchangeLimit',
                'startAt',
                'endAt',
                ['costs', [
                    'materialExchangeId',
                    'costGroupId',
                    'seq',
                    'resourceType',
                    'resourceId',
                    'quantity',
                ]],
                ['materialExchangeRelationParents', [
                    'id',
                    'description',
                    'assetbundleName',
                    ['materialExchangeRelationChildren', [
                        'materialExchangeId',
                        'materialExchangeCostGroupId',
                    ]],
                ]],
            ]],
            ['materialExchangeDisplayResourceGroups', [
                'id',
                'groupId',
                'seq',
                'resourceType',
                'resourceId',
                'assetbundleName',
            ]],
            'materialExchangeFreebieGroupJson',
            ['materialExchangeFreebies', [
                'id',
                'materialExchangeFreebieGroupId',
                'materialExchangeFreebieTypeId',
                'resourceBoxId',
            ]],
        ],
        'materialExchangeSummary': [
            'id',
            'seq',
            'exchangeCategory',
            'materialExchangeType',
            'materialExchangeDisplayResourceGroupId',
            'name',
            'assetbundleName',
            'startAt',
            'endAt',
            'notificationRemainHour',
            ['materialExchanges', [
                'id',
                'materialExchangeSummaryId',
                'seq',
                'displayName',
                'isDisplayQuantity',
                'thumbnailAssetbundleName',
                'resourceBoxId',
                'refreshCycle',
                'exchangeLimit',
                'startAt',
                'endAt',
                ['costs', [
                    'materialExchangeId',
                    'costGroupId',
                    'seq',
                    'resourceType',
                    'resourceId',
                    'quantity',
                ]],
                ['materialExchangeRelationParents', [
                    'id',
                    'description',
                    'assetbundleName',
                    ['materialExchangeRelationChildren', [
                        'materialExchangeId',
                        'materialExchangeCostGroupId',
                    ]],
                ]],
            ]],
            ['materialExchangeDisplayResourceGroups', [
                'id',
                'groupId',
                'seq',
                'resourceType',
                'resourceId',
                'assetbundleName',
            ]],
            'materialExchangeFreebieGroupJson',
            ['materialExchangeFreebies', [
                'id',
                'materialExchangeFreebieGroupId',
                'materialExchangeFreebieTypeId',
                'resourceBoxId',
            ]],
        ],
        'materialExchanges': [
            'id',
            'materialExchangeSummaryId',
            'seq',
            'displayName',
            'isDisplayQuantity',
            'thumbnailAssetbundleName',
            'resourceBoxId',
            'refreshCycle',
            'exchangeLimit',
            'startAt',
            'endAt',
            ['costs', [
                'materialExchangeId',
                'costGroupId',
                'seq',
                'resourceType',
                'resourceId',
                'quantity',
            ]],
            ['materialExchangeRelationParents', [
                'id',
                'description',
                'assetbundleName',
                ['materialExchangeRelationChildren', [
                    'materialExchangeId',
                    'materialExchangeCostGroupId',
                ]],
            ]],
        ],
        'missionReward': [
            'resourceBoxId',
        ],
        'missionRewards': [
            'resourceBoxId',
        ],
        'music': [
            'id',
            'seq',
            'releaseConditionId',
            ['categories', [
                'musicCategoryName',
                'startAt',
            ]],
            'title',
            'pronunciation',
            'creatorArtistId',
            'lyricist',
            'composer',
            'arranger',
            'dancerCount',
            'selfDancerPosition',
            'assetbundleName',
            'publishedAt',
            'releasedAt',
            'fillerSec',
            ['infos', [
                'title',
                'creator',
                'lyricist',
                'composer',
                'arranger',
            ]],
            'musicCollaborationId',
            'isNewlyWrittenMusic',
            'isFullLength',
        ],
        'musicDifficulties': [
            'id',
            'musicId',
            'musicDifficulty',
            'playLevel',
            'totalNoteCount',
        ],
        'musicDifficulty': [
            'id',
            'musicId',
            'musicDifficulty',
            'playLevel',
            'totalNoteCount',
        ],
        'musicTag': [
            'musicId',
            'musicTag',
        ],
        'musicTags': [
            'musicId',
            'musicTag',
        ],
        'musicVocal': [
            'id',
            'musicId',
            'musicVocalType',
            'seq',
            'releaseConditionId',
            'caption',
            ['characters', [
                'id',
                'musicId',
                'musicVocalId',
                'characterType',
                'characterId',
                'seq',
            ]],
            'assetbundleName',
            'specialSeasonId',
            'archiveDisplayType',
            'archivePublishedAt',
        ],
        'musicVocalCharacter': [
            'id',
            'musicId',
            'musicVocalId',
            'characterType',
            'characterId',
            'seq',
        ],
        'musicVocalCharacters': [
            'id',
            'musicId',
            'musicVocalId',
            'characterType',
            'characterId',
            'seq',
        ],
        'musicVocals': [
            'id',
            'musicId',
            'musicVocalType',
            'seq',
            'releaseConditionId',
            'caption',
            ['characters', [
                'id',
                'musicId',
                'musicVocalId',
                'characterType',
                'characterId',
                'seq',
            ]],
            'assetbundleName',
            'specialSeasonId',
            'archiveDisplayType',
            'archivePublishedAt',
        ],
        'musics': [
            'id',
            'seq',
            'releaseConditionId',
            ['categories', [
                'musicCategoryName',
                'startAt',
            ]],
            'title',
            'pronunciation',
            'creatorArtistId',
            'lyricist',
            'composer',
            'arranger',
            'dancerCount',
            'selfDancerPosition',
            'assetbundleName',
            'publishedAt',
            'releasedAt',
            'fillerSec',
            ['infos', [
                'title',
                'creator',
                'lyricist',
                'composer',
                'arranger',
            ]],
            'musicCollaborationId',
            'isNewlyWrittenMusic',
            'isFullLength',
        ],
        'mysekaiBlueprintMysekaiMaterialCost': [
            'id',
            'mysekaiBlueprintId',
            'mysekaiMaterialId',
            'seq',
            'quantity',
        ],
        'mysekaiBlueprintMysekaiMaterialCosts': [
            'id',
            'mysekaiBlueprintId',
            'mysekaiMaterialId',
            'seq',
            'quantity',
        ],
        'mysekaiCharacterTalk': [
            'id',
            'mysekaiGameCharacterUnitGroupId',
            'mysekaiCharacterTalkConditionGroupId',
            'mysekaiSiteGroupId',
            'mysekaiCharacterTalkTermId',
            'characterArchiveMysekaiCharacterTalkGroupId',
            'assetbundleName',
            'lua',
            'isEnabledForMulti',
        ],
        'mysekaiCharacterTalkPreAction': [
            'id',
            'mysekaiCharacterTalkId',
            'mysekaiCharacterTalkTweetId',
            'mysekaiCharacterTalkFixtureTimelineGroupId',
            'mysekaiCharacterTalkFixtureTogetherCommunicationId',
        ],
        'mysekaiCharacterTalkPreActions': [
            'id',
            'mysekaiCharacterTalkId',
            'mysekaiCharacterTalkTweetId',
            'mysekaiCharacterTalkFixtureTimelineGroupId',
            'mysekaiCharacterTalkFixtureTogetherCommunicationId',
        ],
        'mysekaiCharacterTalkTweet': [
            'id',
            'motionName',
            'emoticonName',
            'expressionEyeName',
            'expressionMouthName',
            'text',
        ],
        'mysekaiCharacterTalkTweets': [
            'id',
            'motionName',
            'emoticonName',
            'expressionEyeName',
            'expressionMouthName',
            'text',
        ],
        'mysekaiCharacterTalks': [
            'id',
            'mysekaiGameCharacterUnitGroupId',
            'mysekaiCharacterTalkConditionGroupId',
            'mysekaiSiteGroupId',
            'mysekaiCharacterTalkTermId',
            'characterArchiveMysekaiCharacterTalkGroupId',
            'assetbundleName',
            'lua',
            'isEnabledForMulti',
        ],
        'mysekaiFixture': [
            'id',
            'mysekaiFixtureType',
            'name',
            'pronunciation',
            'flavorText',
            'seq',
            'gridSize',
            'colorCode',
            'mysekaiFixtureMainGenreId',
            'mysekaiFixtureSubGenreId',
            'mysekaiFixtureHandleType',
            'mysekaiSettableSiteType',
            'mysekaiSettableLayoutType',
            'mysekaiFixturePutType',
            ['mysekaiFixtureAnotherColors', [
                'textureId',
                'colorCode',
            ]],
            'mysekaiFixtureGameCharacterGroupPerformanceBonusId',
            'mysekaiFixturePutSoundId',
            'mysekaiFixtureFootstepId',
            'mysekaiFixtureTagGroup',
            'isAssembled',
            'isDisassembled',
            'mysekaiFixturePlayerActionType',
            'isGameCharacterAction',
            'assetbundleName',
        ],
        'mysekaiFixtureAnotherColor': [
            'textureId',
            'colorCode',
        ],
        'mysekaiFixtureAnotherColors': [
            'textureId',
            'colorCode',
        ],
        'mysekaiFixtures': [
            'id',
            'mysekaiFixtureType',
            'name',
            'pronunciation',
            'flavorText',
            'seq',
            'gridSize',
            'colorCode',
            'mysekaiFixtureMainGenreId',
            'mysekaiFixtureSubGenreId',
            'mysekaiFixtureHandleType',
            'mysekaiSettableSiteType',
            'mysekaiSettableLayoutType',
            'mysekaiFixturePutType',
            ['mysekaiFixtureAnotherColors', [
                'textureId',
                'colorCode',
            ]],
            'mysekaiFixtureGameCharacterGroupPerformanceBonusId',
            'mysekaiFixturePutSoundId',
            'mysekaiFixtureFootstepId',
            'mysekaiFixtureTagGroup',
            'isAssembled',
            'isDisassembled',
            'mysekaiFixturePlayerActionType',
            'isGameCharacterAction',
            'assetbundleName',
        ],
        'mysekaiGameCharacterUnitGroup': [
            'id',
            'gameCharacterUnitId1',
            'gameCharacterUnitId2',
            'gameCharacterUnitId3',
            'gameCharacterUnitId4',
            'gameCharacterUnitId5',
        ],
        'mysekaiGameCharacterUnitGroups': [
            'id',
            'gameCharacterUnitId1',
            'gameCharacterUnitId2',
            'gameCharacterUnitId3',
            'gameCharacterUnitId4',
            'gameCharacterUnitId5',
        ],
        'ngWord': [
            'word',
        ],
        'ngWords': [
            'word',
        ],
        'ongoingMission': [
            'id',
            'ongoingMissionType',
            'seq',
            'sentence',
            'requirement',
            ['rewards', [
                'resourceBoxId',
            ]],
            'startAt',
            'endAt',
        ],
        'ongoingMissions': [
            'id',
            'ongoingMissionType',
            'seq',
            'sentence',
            'requirement',
            ['rewards', [
                'resourceBoxId',
            ]],
            'startAt',
            'endAt',
        ],
        'panelMissionReward': [
            'resourceBoxId',
        ],
        'panelMissionRewards': [
            'resourceBoxId',
        ],
        'releaseCondition': [
            'id',
            'sentence',
            'releaseConditionType',
            'releaseConditionTypeId',
            'releaseConditionTypeId2',
            'releaseConditionTypeLevel',
            'releaseConditionTypeQuantity',
        ],
        'releaseConditions': [
            'id',
            'sentence',
            'releaseConditionType',
            'releaseConditionTypeId',
            'releaseConditionTypeId2',
            'releaseConditionTypeLevel',
            'releaseConditionTypeQuantity',
        ],
        'resource': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'resources': [
            'customProfileResourceType',
            'id',
            'seq',
            'name',
            'pronunciation',
            'resourceLoadType',
            'resourceLoadVal',
            'fileName',
            'characterId',
            'customProfileResourceCollectionType',
            'groupId',
        ],
        'returnMission': [
            'returnMissionGroupId',
            'id',
            'seq',
            'returnMissionType',
            'requirement',
            'sentence',
            'resourceBoxId',
        ],
        'returnMissions': [
            'returnMissionGroupId',
            'id',
            'seq',
            'returnMissionType',
            'requirement',
            'sentence',
            'resourceBoxId',
        ],
        'sekaiEchoCardMission': [
            'cardGroup',
            'sekaiEchoCardMissionType',
            'seq',
            'sentence',
            'keyMission',
            'resourceBoxId',
        ],
        'sekaiEchoCardMissions': [
            'cardGroup',
            'sekaiEchoCardMissionType',
            'seq',
            'sentence',
            'keyMission',
            'resourceBoxId',
        ],
        'sekaiEchoHonor': [
            'eventId',
            'sekaiLevel',
            'honorId',
        ],
        'sekaiEchoHonorMission': [
            'sekaiLevel',
            'sekaiEchoHonorMissionType',
            'seq',
            'requirement',
            'sentence',
        ],
        'sekaiEchoHonorMissions': [
            'sekaiLevel',
            'sekaiEchoHonorMissionType',
            'seq',
            'requirement',
            'sentence',
        ],
        'sekaiEchoHonors': [
            'eventId',
            'sekaiLevel',
            'honorId',
        ],
        'sekaiEchoMission': [
            'id',
            'sekaiEchoMissionType',
            'seq',
            'sentence',
            'requirement',
            ['rewards', [
                'resourceBoxId',
            ]],
        ],
        'sekaiEchoMissions': [
            'id',
            'sekaiEchoMissionType',
            'seq',
            'sentence',
            'requirement',
            ['rewards', [
                'resourceBoxId',
            ]],
        ],
        'sekaiEchoPointExchange': [
            'resourceType',
            'resourceId',
            'quantity',
            'echoPoint',
            'seq',
        ],
        'sekaiEchoPointExchanges': [
            'resourceType',
            'resourceId',
            'quantity',
            'echoPoint',
            'seq',
        ],
        'sekaiEchoStories': [
            'id',
            'groupId',
            'storyType',
            'eventId',
            'honorGroupId',
            'gameCharacterId',
            'characterEventSeq',
            'musicId',
            'stampId',
            'startAt',
            'unit',
            'assetBundleName',
            'showGameCharacterId',
        ],
        'sekaiEchoStory': [
            'id',
            'groupId',
            'storyType',
            'eventId',
            'honorGroupId',
            'gameCharacterId',
            'characterEventSeq',
            'musicId',
            'stampId',
            'startAt',
            'unit',
            'assetBundleName',
            'showGameCharacterId',
        ],
        'sekaiEchoStoryGroup': [
            'groupId',
            'groupName',
        ],
        'sekaiEchoStoryGroups': [
            'groupId',
            'groupName',
        ],
        'sekaiEchoUnitAb': [
            'unit',
            'seq',
            'assetBundleName',
            'pvAssetBundleName',
            'picAssetBundleName',
        ],
        'sekaiEchoUnitAbs': [
            'unit',
            'seq',
            'assetBundleName',
            'pvAssetBundleName',
            'picAssetBundleName',
        ],
        'sekaiEchoUnitCharacter': [
            'gameCharacterId',
            'unit',
            'seq',
            'assetbundleName',
        ],
        'sekaiEchoUnitCharacters': [
            'gameCharacterId',
            'unit',
            'seq',
            'assetbundleName',
        ],
        'shiningExchange': [
            'id',
            'shiningExchangeType',
            'seq',
            'resourceBoxId',
            'cost',
            'refreshCycle',
            'exchangeLimit',
            'startAt',
            'endAt',
        ],
        'shiningExchanges': [
            'id',
            'shiningExchangeType',
            'seq',
            'resourceBoxId',
            'cost',
            'refreshCycle',
            'exchangeLimit',
            'startAt',
            'endAt',
        ],
        'shopItem': [
            'id',
            'shopId',
            'seq',
            'releaseConditionId',
            'resourceBoxId',
            ['costs', [
                'cost',
            ]],
            'startAt',
            'endAt',
        ],
        'shopItemCost': [
            'cost',
        ],
        'shopItemCosts': [
            'cost',
        ],
        'shopItems': [
            'id',
            'shopId',
            'seq',
            'releaseConditionId',
            'resourceBoxId',
            ['costs', [
                'cost',
            ]],
            'startAt',
            'endAt',
        ],
        'specialTrainingCost': [
            'cardId',
            'seq',
            'cost',
        ],
        'specialTrainingCosts': [
            'cardId',
            'seq',
            'cost',
        ],
        'stamp': [
            'id',
            'stampType',
            'seq',
            'name',
            'assetbundleName',
            'balloonAssetbundleName',
            'characterId1',
            'characterId2',
            'characterId3',
            'characterId4',
            'characterId5',
            'gameCharacterUnitId',
            'archiveDisplayType',
            'archivePublishedAt',
            'description',
        ],
        'stamps': [
            'id',
            'stampType',
            'seq',
            'name',
            'assetbundleName',
            'balloonAssetbundleName',
            'characterId1',
            'characterId2',
            'characterId3',
            'characterId4',
            'characterId5',
            'gameCharacterUnitId',
            'archiveDisplayType',
            'archivePublishedAt',
            'description',
        ],
        'topic': [
            'id',
            'topicType',
            'topicTypeId',
            'releaseConditionId',
        ],
        'topics': [
            'id',
            'topicType',
            'topicTypeId',
            'releaseConditionId',
        ],
        'translateMusicInfo': [
            'title',
            'creator',
            'lyricist',
            'composer',
            'arranger',
        ],
        'translateMusicInfos': [
            'title',
            'creator',
            'lyricist',
            'composer',
            'arranger',
        ],
        'virtualItem': [
            'id',
            'virtualItemCategory',
            'seq',
            'priority',
            'name',
            'assetbundleName',
            'costVirtualCoin',
            'costJewel',
            'effectAssetbundleName',
            'effectExpressionType',
            'virtualItemLabelType',
            'gameCharacterUnitId',
            'unit',
            'subGameCharacterId',
        ],
        'virtualItems': [
            'id',
            'virtualItemCategory',
            'seq',
            'priority',
            'name',
            'assetbundleName',
            'costVirtualCoin',
            'costJewel',
            'effectAssetbundleName',
            'effectExpressionType',
            'virtualItemLabelType',
            'gameCharacterUnitId',
            'unit',
            'subGameCharacterId',
        ],
        'virtualItemses': [
            'id',
            'virtualItemLabelType',
        ],
        'virtualLive': [
            'id',
            'virtualLiveType',
            'virtualLivePlatform',
            'seq',
            'name',
            'assetbundleName',
            'screenMvMusicVocalId',
            'subGameCharacterPenlightColorGroupId',
            'startAt',
            'endAt',
            'virtualLiveGroupId',
            'rankingAnnounceAt',
            'archiveReleaseConditionId',
            ['virtualLiveSetlists', [
                'id',
                'virtualLiveId',
                'seq',
                'virtualLiveSetlistType',
                'assetbundleName',
                'virtualLiveStageId',
                'musicId',
                'musicVocalId',
                'character3dId1',
                'character3dId2',
                'character3dId3',
                'character3dId4',
                'character3dId5',
                'character3dId6',
            ]],
            ['virtualLiveBeginnerSchedules', [
                'id',
                'virtualLiveId',
                'dayOfWeek',
                'startTime',
                'endTime',
            ]],
            ['virtualLiveSchedules', [
                'id',
                'virtualLiveId',
                'seq',
                'startAt',
                'endAt',
                'noticeGroupId',
                'isAfterEvent',
            ]],
            ['virtualLiveCharacters', [
                'gameCharacterUnitId',
                'subGameCharacter2dId',
                'virtualLivePerformanceType',
            ]],
            ['virtualLiveRewards', [
                'virtualLiveType',
                'resourceBoxId',
            ]],
            'virtualLiveWaitingRoom',
            ['virtualItems', [
                'id',
                'virtualItemLabelType',
            ]],
            ['virtualLiveAppeals', [
                'id',
                'virtualLiveId',
                'virtualLiveStageStatus',
                'appealText',
            ]],
            ['virtualLiveBackgroundMusics', [
                'id',
                'virtualLiveId',
                'backgroundMusicId',
            ]],
            'virtualLiveInformation',
        ],
        'virtualLiveAppeal': [
            'id',
            'virtualLiveId',
            'virtualLiveStageStatus',
            'appealText',
        ],
        'virtualLiveAppeals': [
            'id',
            'virtualLiveId',
            'virtualLiveStageStatus',
            'appealText',
        ],
        'virtualLiveBackgroundMusic': [
            'id',
            'virtualLiveId',
            'backgroundMusicId',
        ],
        'virtualLiveBackgroundMusics': [
            'id',
            'virtualLiveId',
            'backgroundMusicId',
        ],
        'virtualLiveBeginnerSchedule': [
            'id',
            'virtualLiveId',
            'dayOfWeek',
            'startTime',
            'endTime',
        ],
        'virtualLiveBeginnerSchedules': [
            'id',
            'virtualLiveId',
            'dayOfWeek',
            'startTime',
            'endTime',
        ],
        'virtualLiveCharacter': [
            'gameCharacterUnitId',
            'subGameCharacter2dId',
            'virtualLivePerformanceType',
        ],
        'virtualLiveCharacters': [
            'gameCharacterUnitId',
            'subGameCharacter2dId',
            'virtualLivePerformanceType',
        ],
        'virtualLiveInformation': [
            'virtualLiveId',
            'summary',
            'description',
        ],
        'virtualLiveInformations': [
            'virtualLiveId',
            'summary',
            'description',
        ],
        'virtualLiveReward': [
            'virtualLiveType',
            'resourceBoxId',
        ],
        'virtualLiveRewards': [
            'virtualLiveType',
            'resourceBoxId',
        ],
        'virtualLiveSchedule': [
            'id',
            'virtualLiveId',
            'seq',
            'startAt',
            'endAt',
            'noticeGroupId',
            'isAfterEvent',
        ],
        'virtualLiveSchedules': [
            'id',
            'virtualLiveId',
            'seq',
            'startAt',
            'endAt',
            'noticeGroupId',
            'isAfterEvent',
        ],
        'virtualLiveSetlist': [
            'id',
            'virtualLiveId',
            'seq',
            'virtualLiveSetlistType',
            'assetbundleName',
            'virtualLiveStageId',
            'musicId',
            'musicVocalId',
            'character3dId1',
            'character3dId2',
            'character3dId3',
            'character3dId4',
            'character3dId5',
            'character3dId6',
        ],
        'virtualLiveSetlists': [
            'id',
            'virtualLiveId',
            'seq',
            'virtualLiveSetlistType',
            'assetbundleName',
            'virtualLiveStageId',
            'musicId',
            'musicVocalId',
            'character3dId1',
            'character3dId2',
            'character3dId3',
            'character3dId4',
            'character3dId5',
            'character3dId6',
        ],
        'virtualLives': [
            'id',
            'virtualLiveType',
            'virtualLivePlatform',
            'seq',
            'name',
            'assetbundleName',
            'screenMvMusicVocalId',
            'subGameCharacterPenlightColorGroupId',
            'startAt',
            'endAt',
            'virtualLiveGroupId',
            'rankingAnnounceAt',
            'archiveReleaseConditionId',
            ['virtualLiveSetlists', [
                'id',
                'virtualLiveId',
                'seq',
                'virtualLiveSetlistType',
                'assetbundleName',
                'virtualLiveStageId',
                'musicId',
                'musicVocalId',
                'character3dId1',
                'character3dId2',
                'character3dId3',
                'character3dId4',
                'character3dId5',
                'character3dId6',
            ]],
            ['virtualLiveBeginnerSchedules', [
                'id',
                'virtualLiveId',
                'dayOfWeek',
                'startTime',
                'endTime',
            ]],
            ['virtualLiveSchedules', [
                'id',
                'virtualLiveId',
                'seq',
                'startAt',
                'endAt',
                'noticeGroupId',
                'isAfterEvent',
            ]],
            ['virtualLiveCharacters', [
                'gameCharacterUnitId',
                'subGameCharacter2dId',
                'virtualLivePerformanceType',
            ]],
            ['virtualLiveRewards', [
                'virtualLiveType',
                'resourceBoxId',
            ]],
            ['virtualLiveWaitingRoom', ('id', 'lobbyAssetbundleName', 'startAt', 'endAt',)],
            ['virtualItems', [
                'id',
                'virtualItemLabelType',
            ]],
            ['virtualLiveAppeals', [
                'id',
                'virtualLiveId',
                'virtualLiveStageStatus',
                'appealText',
            ]],
            ['virtualLiveBackgroundMusics', [
                'id',
                'virtualLiveId',
                'backgroundMusicId',
            ]],
            ['virtualLiveInformation', ('virtualLiveId', 'summary', 'description',)],
        ],
        'wording': [
            'wordingKey',
            'value',
        ],
        'wordings': [
            'wordingKey',
            'value',
        ],
    }
)
