structures = {
    "actionSets": [
        "id",
        "areaId",
        "actionSetType",
        "isNextGrade",
        "scenarioId",
        "scriptId",
        "characterIds",
        "archiveDisplayType",
        "archivePublishedAt",
        "releaseConditionId",
    ],
    "areaItemLevels": [
        "areaItemId",
        "level",
        "targetUnit",
        "targetCardAttr",
        "targetGameCharacterId",
        "power1BonusRate",
        "power1AllMatchBonusRate",
        "power2BonusRate",
        "power2AllMatchBonusRate",
        "power3BonusRate",
        "power3AllMatchBonusRate",
        "sentence",
    ],
    "bondsHonors": [
        "id",
        "seq",
        "bondsGroupId",
        "gameCharacterUnitId1",
        "gameCharacterUnitId2",
        "honorRarity",
        "name",
        "pronunciation",
        "description",
        ["levels", ["id", "bondsHonorId", "level", "description"]],
        "configurableUnitVirtualSinger",
    ],
    "cardCostume3ds": ["cardId", "costume3dId"],
    "cardEpisodes": [
        "id",
        "cardId",
        "title",
        "scenarioId",
        "releaseConditionId",
        "power1BonusFixed",
        "power2BonusFixed",
        "power3BonusFixed",
        ["costs", ["resourceId", "resourceType", "resourceLevel", "quantity"]],
        "cardEpisodePartType",
    ],
    "cards": [
        "id",
        "seq",
        "characterId",
        "cardRarityType",
        "specialTrainingPower1BonusFixed",
        "specialTrainingPower2BonusFixed",
        "specialTrainingPower3BonusFixed",
        "attr",
        "supportUnit",
        "skillId",
        "cardSkillName",
        "specialTrainingSkillId",
        "specialTrainingSkillName",
        "prefix",
        "assetbundleName",
        "gachaPhrase",
        "releaseAt",
        "archiveDisplayType",
        "archivePublishedAt",
        "cardSupplyId",
        "cardParameters",
        [
            "specialTrainingCosts",
            [
                "cardId",
                "seq",
                ["cost", ("resourceId", "resourceType", "resourceLevel", "quantity")],
            ],
        ],
        "specialTrainingRewardResourceBoxId",
        ["masterLessonAchieveResources", ["masterRank", "resources"]],
        "initialSpecialTrainingStatus",
    ],
    "challengeLiveHighScoreRewards": [
        "id",
        "characterId",
        "highScore",
        "resourceBoxId",
    ],
    "challengeLiveStages": ["characterId", "rank", "nextStageChallengePoint"],
    "character3ds": [
        "id",
        "characterId",
        "unit",
        "headCostume3dId",
        "hairCostume3dId",
        "bodyCostume3dId",
        "lookAtLimitX",
        "lookAtLimitY",
        "name",
    ],
    "characterArchiveVoices": [
        "id",
        "groupId",
        "gameCharacterId",
        "unit",
        "characterArchiveVoiceType",
        "displayPhrase",
        "displayPhrase2",
        "characterArchiveVoiceTagId",
        "externalId",
        "assetName",
        "isNextGrade",
        "displayStartAt",
    ],
    "characterRanks": [
        "id",
        "characterId",
        "characterRank",
        "power1BonusRate",
        "power2BonusRate",
        "power3BonusRate",
        "rewardResourceBoxIds",
        ["characterRankAchieveResources", ["resources"]],
    ],
    "cheerfulCarnivalPartyNames": [
        "id",
        "partyName",
        "gameCharacterUnitId1",
        "gameCharacterUnitId2",
        "gameCharacterUnitId3",
        "gameCharacterUnitId4",
        "gameCharacterUnitId5",
    ],
    "episodeCharacters": ["id", "seq", "character2dId", "storyType", "episodeId"],
    "eventDeckBonuses": [
        "id",
        "eventId",
        "gameCharacterUnitId",
        "cardAttr",
        "bonusRate",
    ],
    "eventExchangeSummaries": [
        "id",
        "eventId",
        "startAt",
        "endAt",
        [
            "eventExchanges",
            [
                "id",
                "eventExchangeSummaryId",
                "gameCharacterId",
                "seq",
                "resourceBoxId",
                "exchangeLimit",
                ["eventExchangeCost", ("resourceQuantity",)],
            ],
        ],
        "assetbundleName",
    ],
    "events": [
        "id",
        "eventType",
        "name",
        "assetbundleName",
        "bgmAssetbundleName",
        "eventPointAssetbundleName",
        "eventOnlyComponentDisplayStartAt",
        "standbyScreenDisplayStartAt",
        "startAt",
        "aggregateAt",
        "rankingAnnounceAt",
        "distributionStartAt",
        "eventOnlyComponentDisplayEndAt",
        "closedAt",
        "distributionEndAt",
        "virtualLiveId",
        "unit",
        [
            "eventRankingRewardRanges",
            [
                "fromRank",
                "toRank",
                [
                    "eventRankingRewards",
                    ["resourceBoxId", "rewardConditionType", "conditionValue"],
                ],
            ],
        ],
    ],
    "eventStories": [
        "id",
        "eventId",
        "outline",
        "bannerGameCharacterUnitId",
        "assetbundleName",
        [
            "eventStoryEpisodes",
            [
                "id",
                "eventStoryId",
                "gameCharacterId",
                "episodeNo",
                "title",
                "assetbundleName",
                "scenarioId",
                "releaseConditionId",
                ["episodeRewards", ["startAt", "endAt", "resourceBoxId"]],
            ],
        ],
    ],
    "gachaCeilExchangeSummaries": [
        "id",
        "seq",
        "assetbundleName",
        "startAt",
        "endAt",
        [
            "gachaCeilExchanges",
            [
                "id",
                "gachaCeilExchangeSummaryId",
                "seq",
                "resourceBoxId",
                "exchangeLimit",
                "gachaCeilExchangeLabelType",
                "substituteLimit",
                ["gachaCeilExchangeCost", ("quantity", "resourceType", "resourceId")],
                [
                    "gachaCeilExchangeSubstituteCosts",
                    ["id", "resourceType", "resourceId", "substituteQuantity"],
                ],
            ],
        ],
        "gachaCeilItemId",
    ],
    "gachas": [
        "id",
        "gachaType",
        "name",
        "seq",
        "assetbundleName",
        "startAt",
        "endAt",
        "isShowPeriod",
        "spinLimit",
        "gachaCeilItemId",
        "wishSelectCount",
        "wishFixedSelectCount",
        "wishLimitedSelectCount",
        "gachaBonusId",
        "drawableGachaHour",
        ["gachaCardRarityRates", ["cardRarityType", "lotteryType", "rate"]],
        [
            "gachaDetails",
            [
                "id",
                "gachaId",
                "cardId",
                "weight",
                "fixedBonusWeight",
                "isWish",
                "gachaDetailWishType",
            ],
        ],
        [
            "gachaBehaviors",
            [
                "id",
                "gachaId",
                "gachaBehaviorType",
                "costResourceType",
                "costResourceId",
                "costResourceQuantity",
                "spinCount",
                "executeLimit",
                "gachaExtraId",
                "groupId",
                "priority",
                "resourceCategory",
                "gachaSpinnableType",
            ],
        ],
        ["gachaPickups", ["gachaId", "cardId"]],
        [
            "gachaInformation",
            (
                "gachaId",
                "summary",
                "description",
                "bubbleAssetbundleName",
                "bubbleText",
            ),
        ],
        "dailySpinLimit",
        "gachaBonusItemReceivableRewardGroupId",
        "gachaFreebieGroupId",
    ],
    "honors": [
        "id",
        "seq",
        "groupId",
        "honorRarity",
        "name",
        "assetbundleName",
        "honorTypeId",
        "honorMissionType",
        "startAt",
        [
            "levels",
            [
                "level",
                "bonus",
                "description",
                "startAt",
                "assetbundleName",
                "honorRarity",
            ],
        ],
    ],
    "liveMissions": [
        "id",
        "liveMissionPeriodId",
        "liveMissionType",
        "requirement",
        ["rewards", ["resourceBoxId"]],
    ],
    "masterLessonRewards": ["cardId", "masterRank", "resourceBoxId", "id"],
    "materialExchangeSummaries": [
        "id",
        "seq",
        "exchangeCategory",
        "materialExchangeType",
        "materialExchangeDisplayResourceGroupId",
        "name",
        "assetbundleName",
        "startAt",
        "endAt",
        "notificationRemainHour",
        [
            "materialExchanges",
            [
                "id",
                "materialExchangeSummaryId",
                "seq",
                "displayName",
                "isDisplayQuantity",
                "thumbnailAssetbundleName",
                "resourceBoxId",
                "refreshCycle",
                "exchangeLimit",
                "startAt",
                "endAt",
                [
                    "costs",
                    [
                        "materialExchangeId",
                        "costGroupId",
                        "seq",
                        "resourceType",
                        "resourceId",
                        "quantity",
                    ],
                ],
                "materialExchangeRelationParents",
            ],
        ],
        "materialExchangeDisplayResourceGroups",
        "materialExchangeFreebieGroupJson",
        "materialExchangeFreebies",
    ],
    "musicDifficulties": [
        "id",
        "musicId",
        "musicDifficulty",
        "playLevel",
        "totalNoteCount",
    ],
    "musics": [
        "id",
        "seq",
        "releaseConditionId",
        ["categories", ["musicCategoryName", "startAt"]],
        "title",
        "pronunciation",
        "creatorArtistId",
        "lyricist",
        "composer",
        "arranger",
        "dancerCount",
        "selfDancerPosition",
        "assetbundleName",
        "publishedAt",
        "releasedAt",
        "fillerSec",
        ["infos", ["title", "creator", "lyricist", "composer", "arranger"]],
        "musicCollaborationId",
        "isNewlyWrittenMusic",
        "isFullLength",
    ],
    "musicTags": ["musicId", "musicTag"],
    "musicVocals": [
        "id",
        "musicId",
        "musicVocalType",
        "seq",
        "releaseConditionId",
        "caption",
        [
            "characters",
            ["id", "musicId", "musicVocalId", "characterType", "characterId", "seq"],
        ],
        "assetbundleName",
        "specialSeasonId",
        "archiveDisplayType",
        "archivePublishedAt",
    ],
    "ngWords": ["word"],
    "releaseConditions": [
        "id",
        "sentence",
        "releaseConditionType",
        "releaseConditionTypeId",
        "releaseConditionTypeId2",
        "releaseConditionTypeLevel",
        "releaseConditionTypeQuantity",
    ],
    "returnMissions": [
        "returnMissionGroupId",
        "id",
        "seq",
        "returnMissionType",
        "requirement",
        "sentence",
        "resourceBoxId",
    ],
    "shopItems": [
        "id",
        "shopId",
        "seq",
        "releaseConditionId",
        "resourceBoxId",
        [
            "costs",
            [["cost", ("resourceId", "resourceType", "resourceLevel", "quantity")]],
        ],
        "startAt",
        "endAt",
    ],
    "stamps": [
        "id",
        "stampType",
        "seq",
        "name",
        "assetbundleName",
        "balloonAssetbundleName",
        "characterId1",
        "characterId2",
        "characterId3",
        "characterId4",
        "characterId5",
        "gameCharacterUnitId",
        "archiveDisplayType",
        "archivePublishedAt",
        "description",
    ],
    "topics": ["id", "topicType", "topicTypeId", "releaseConditionId"],
    "virtualItems": [
        "id",
        "virtualItemCategory",
        "seq",
        "priority",
        "name",
        "assetbundleName",
        "costVirtualCoin",
        "costJewel",
        "effectAssetbundleName",
        "effectExpressionType",
        "virtualItemLabelType",
        "gameCharacterUnitId",
        "unit",
        "subGameCharacterId",
    ],
    "virtualLives": [
        "id",
        "virtualLiveType",
        "virtualLivePlatform",
        "seq",
        "name",
        "assetbundleName",
        "screenMvMusicVocalId",
        "subGameCharacterPenlightColorGroupId",
        "startAt",
        "endAt",
        "virtualLiveGroupId",
        "rankingAnnounceAt",
        "archiveReleaseConditionId",
        [
            "virtualLiveSetlists",
            [
                "id",
                "virtualLiveId",
                "seq",
                "virtualLiveSetlistType",
                "assetbundleName",
                "virtualLiveStageId",
                "musicId",
                "musicVocalId",
                "character3dId1",
                "character3dId2",
                "character3dId3",
                "character3dId4",
                "character3dId5",
                "character3dId6",
            ],
        ],
        [
            "virtualLiveBeginnerSchedules",
            ["id", "virtualLiveId", "dayOfWeek", "startTime", "endTime"],
        ],
        [
            "virtualLiveSchedules",
            [
                "id",
                "virtualLiveId",
                "seq",
                "startAt",
                "endAt",
                "noticeGroupId",
                "isAfterEvent",
            ],
        ],
        [
            "virtualLiveCharacters",
            [
                "gameCharacterUnitId",
                "subGameCharacter2dId",
                "virtualLivePerformanceType",
            ],
        ],
        ["virtualLiveRewards", ["virtualLiveType", "resourceBoxId"]],
        ["virtualLiveWaitingRoom", ("id", "lobbyAssetbundleName", "startAt", "endAt")],
        [
            "virtualItems",
            [
                "id",
                "virtualItemLabelType",
            ],
        ],
        [
            "virtualLiveAppeals",
            ["id", "virtualLiveId", "virtualLiveStageStatus", "appealText"],
        ],
        ["virtualLiveBackgroundMusics", ["id", "virtualLiveId", "backgroundMusicId"]],
        ["virtualLiveInformation", ("virtualLiveId", "summary", "description")],
    ],
    "wordings": ["wordingKey", "value"],
    "sekaiEchoStories": [
        "id",
        "groupId",
        "storyType",
        "eventId",
        "honorGroupId",
        "gameCharacterId",
        "characterEventSeq",
        "musicId",
        "stampId",
        "startAt",
        "unit",
        "assetBundleName",
        "showGameCharacterId",
    ],
    "sekaiEchoStoryGroups": ["groupId", "groupName"],
    "sekaiEchoUnitCharacters": [
        "gameCharacterId",
        "unit",
        "seq",
        "assetBundleName",
    ],
    "sekaiEchoUnitAbs": [
        "unit",
        "seq",
        "assetBundleName",
        "pvAssetBundleName",
        "picAssetBundleName",
    ],
    "sekaiEchoMissions": [
        "id",
        "sekaiEchoMissionType",
        "seq",
        "sentence",
        "requirement",
        ["rewards", ["resourceBoxId"]],
    ],
    "sekaiEchoCardMissions": [
        "cardGroup",
        "sekaiEchoCardMissionType",
        "seq",
        "sentence",
        "keyMission",
        "resourceBoxId",
    ],
    "sekaiEchoHonors": ["eventId", "sekaiLevel", "honorId"],
    "sekaiEchoHonorMissions": [
        "sekaiLevel",
        "sekaiEchoHonorMissionType",
        "seq",
        "requirement",
        "sentence",
    ],
    "sekaiEchoPointExchanges": [
        "resourceType",
        "resourceId",
        "quantity",
        "echoPoint",
        "seq",
    ],
    "shiningExchanges": [
        "id",
        "shiningExchangeType",
        "seq",
        "resourceBoxId",
        "cost",
        "refreshCycle",
        "exchangeLimit",
        "startAt",
        "endAt",
    ],
    "billingShopItems": [
        "id",
        "seq",
        "billingShopItemType",
        "billingProductGroupId",
        "saleType",
        "name",
        "description",
        "billableLimitType",
        "billableLimitValue",
        "billableLimitResetIntervalType",
        "billableLimitResetIntervalValue",
        "assetbundleName",
        "resourceBoxId",
        "bonusResourceBoxId",
        "label",
        "startAt",
        "endAt",
        "purchaseOption",
        "billingShopTabChildId",
    ],
    "ongoingMissions": [
        "id",
        "ongoingMissionType",
        "seq",
        "sentence",
        "requirement",
        ["rewards", ["resourceBoxId"]],
        "startAt",
        "endAt",
    ],
    "jewelShowDialogues": [
        "id",
        "seq",
        "name",
        "assetBundleName",
        "startAt",
        "endAt",
        ["behaviors", ["seq", "billingShopItemId"]],
    ],
    "costume3dFittings": ["billingShopItemId", "characterId", "hairCostume3dId"],
    "costume3dModelDefaultHairs": ["id", "headCostume3dId", "hairCostume3dId", "unit"],
    "costume3dModelNotAvailablePatterns": [
        "id",
        "headCostume3dId",
        "hairCostume3dId",
        "unit",
    ],
    "characterArchiveMysekaiCharacterTalkGroups": [
        "id",
        "seq",
        "archiveDisplayType",
        "characterArchiveMysekaiCharacterTalkGroupTagId",
    ],
    "costume3dColors": ["id", "name"],
    "costume3dGroups": [
        "groupId",
        "name",
        "characterId",
        "rarity",
        "howToObtain",
        "designer",
        "publishedAt",
        "archiveDisplayType",
        "archivePublishedAt",
    ],
    "costume3ds": [
        "id",
        "seq",
        "costume3dGroupId",
        "costume3dType",
        "name",
        "partType",
        "colorId",
        "colorName",
        "characterId",
        "costume3dRarity",
        "howToObtain",
        "_assetbundleName",
        "designer",
        "publishedAt",
        "archiveDisplayType",
        "archivePublishedAt",
    ],
    "customProfileCollectionResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "customProfileEtcResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "customProfileGachas": [
        "id",
        "name",
        "startAt",
        "endAt",
        "assetbundleName",
        "description",
        "notice",
        "customProfileGachaCategory",
        [
            "customProfileGachaBehaviors",
            [
                "id",
                "seq",
                "costResourceType",
                "costResourceId",
                "costResourceQuantity",
                "spinCount",
            ],
        ],
        [
            "customProfileGachaDetails",
            ["id", "customProfileResourceType", "customProfileResourceId", "weight"],
        ],
    ],
    "customProfileGeneralBackgroundResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "customProfileMemberStandingPictureResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "customProfilePlayerInfoResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "customProfileShapeResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "customProfileStoryBackgroundResources": [
        "customProfileResourceType",
        "id",
        "seq",
        "name",
        "pronunciation",
        "resourceLoadType",
        "resourceLoadVal",
        "fileName",
        "characterId",
        "customProfileResourceCollectionType",
        "groupId",
    ],
    "honorMissions": [
        "id",
        "seq",
        "honorMissionType",
        "requirement",
        "sentence",
        ["rewards", ["resourceBoxId"]],
        "startAt",
    ],
    "mysekaiBlueprintMysekaiMaterialCosts": [
        "id",
        "mysekaiBlueprintId",
        "mysekaiMaterialId",
        "seq",
        "quantity",
    ],
    "mysekaiCharacterTalkPreActions": [
        "id",
        "mysekaiCharacterTalkId",
        "mysekaiCharacterTalkTweetId",
        "mysekaiCharacterTalkFixtureTimelineGroupId",
        "mysekaiCharacterTalkFixtureTogetherCommunicationId",
    ],
    "mysekaiCharacterTalkTweets": [
        "id",
        "motionName",
        "emoticonName",
        "expressionEyeName",
        "expressionMouthName",
        "text",
    ],
    "mysekaiCharacterTalks": [
        "id",
        "mysekaiGameCharacterUnitGroupId",
        "mysekaiCharacterTalkConditionGroupId",
        "mysekaiSiteGroupId",
        "mysekaiCharacterTalkTermId",
        "characterArchiveMysekaiCharacterTalkGroupId",
        "assetbundleName",
        "lua",
        "isEnabledForMulti",
    ],
    "mysekaiFixtures": [
        "id",
        "mysekaiFixtureType",
        "name",
        "pronunciation",
        "flavorText",
        "seq",
        "gridSize",
        "colorCode",
        "mysekaiFixtureMainGenreId",
        "mysekaiFixtureSubGenreId",
        "mysekaiFixtureHandleType",
        "mysekaiSettableSiteType",
        "mysekaiSettableLayoutType",
        "mysekaiFixturePutType",
        ["mysekaiFixtureAnotherColors", ["textureId", "colorCode"]],
        "mysekaiFixtureGameCharacterGroupPerformanceBonusId",
        "mysekaiFixturePutSoundId",
        "mysekaiFixtureFootstepId",
        "mysekaiFixtureTagGroup",
        "isAssembled",
        "isDisassembled",
        "mysekaiFixturePlayerActionType",
        "isGameCharacterAction",
        "assetbundleName",
    ],
    "mysekaiGameCharacterUnitGroups": [
        "id",
        "gameCharacterUnitId1",
        "gameCharacterUnitId2",
        "gameCharacterUnitId3",
        "gameCharacterUnitId4",
        "gameCharacterUnitId5",
    ],
}


def convert_array_to_dict(array_data: list, key_structure: list) -> dict:
    """
    convert array to dict with given structure
    :param array_data: array data
    :param key_structure: json structure of the result dict
    :return: result dict
    """
    result = {}

    for i, key in enumerate(key_structure):
        if isinstance(key, str):
            # if key is string, then assign the value to the key
            if i >= len(array_data):
                continue
            if array_data[i] is not None:
                result[key] = array_data[i]
        elif isinstance(key, list):
            if isinstance(key[1], list):
                # if key is list and the second element is list, then it is a nested list
                result[key[0]] = [
                    convert_array_to_dict(sub_array, key[1])
                    for sub_array in array_data[i]
                    if sub_array is not None
                ]
            elif isinstance(key[1], tuple):
                # if key is list and the second element is tuple, then it is a dict
                result[key[0]] = {
                    key[1][i]: v for i, v in enumerate(array_data[i]) if v is not None
                }

    return result


def restore_compact_data(data: dict) -> list:
    """
    Original Author: TWY
    convert compact data to original data structure
    :param data: dict
    :return: result: list
    """
    enum = data.get("__ENUM__", {})
    column_labels = []
    columns = []
    for column in data:
        if column == "__ENUM__":
            continue
        column_labels.append(column)
        if column in enum:
            columns.append(
                [(None if i is None else enum[column][i]) for i in data[column]]
            )
        else:
            columns.append(data[column])
    num_entries = min(len(column) for column in columns)
    result = []
    for i in range(num_entries):
        result.append({key: column[i] for key, column in zip(column_labels, columns)})
    return result
